#include "camera_protocol.h"

#include <assert.h>
#include <stdio.h>
#include <string.h>

static CameraParseResult feed(CameraProtocolParser *parser,
                              const char *text,
                              CameraProtocolFrame *frame)
{
    CameraParseResult last = CAMERA_PARSE_NONE;
    while (*text != '\0') {
        CameraParseResult current = CameraProtocol_Push(
            parser, (uint8_t)*text++, frame
        );
        if (current != CAMERA_PARSE_NONE) {
            last = current;
        }
    }
    return last;
}

static void make_frame(const char *payload, char *output, size_t output_size)
{
    snprintf(output, output_size, "$%s*%02X\r\n",
             payload, CameraProtocol_Xor(payload));
}

int main(void)
{
    CameraProtocolParser parser;
    CameraProtocolFrame frame;
    char text[96];
    CameraParseResult result;

    CameraProtocol_Init(&parser);
    /* Literal frames are generated by K230 main.make_uart_frame(). */
    result = feed(&parser, "$B,7,1234,1,-32,46,875,50*7D\r\n", &frame);
    assert(result == CAMERA_PARSE_FRAME);
    assert(frame.seq == 7U);
    assert(frame.timestamp_ms == 1234U);
    assert(frame.valid == 1U);
    assert(frame.pos_mm == -32);
    assert(frame.vel_mm_s == 46);
    assert(frame.confidence_permille == 875U);
    assert(frame.target_mm == 50);

    result = feed(&parser, "$B,8,1300,0,0,0,0,-50*7C\r\n", &frame);
    assert(result == CAMERA_PARSE_FRAME);
    assert(frame.valid == 0U);
    assert(frame.target_mm == -50);

    /* Frames without the required target field are deliberately rejected. */
    make_frame("B,6,1200,1,25,-14,800", text, sizeof(text));
    result = feed(&parser, text, &frame);
    assert(result == CAMERA_PARSE_FORMAT_ERROR);

    make_frame("B,9,1400,1,12,-3,901,50", text, sizeof(text));
    text[strlen(text) - 4U] = (text[strlen(text) - 4U] == '0') ? '1' : '0';
    result = feed(&parser, text, &frame);
    assert(result == CAMERA_PARSE_CHECKSUM_ERROR);

    make_frame("B,10,1500,1,12,-3,1001,50", text, sizeof(text));
    result = feed(&parser, text, &frame);
    assert(result == CAMERA_PARSE_FORMAT_ERROR);

    /* A one-digit field must still obey its configured upper bound. */
    make_frame("B,10,1500,2,12,-3,900,50", text, sizeof(text));
    result = feed(&parser, text, &frame);
    assert(result == CAMERA_PARSE_FORMAT_ERROR);

    make_frame("B,10,1500,1,12,-3,900,126", text, sizeof(text));
    result = feed(&parser, text, &frame);
    assert(result == CAMERA_PARSE_FORMAT_ERROR);

    /* Noise and a partial frame must not prevent '$' re-synchronization. */
    feed(&parser, "noise$B,99,broken", &frame);
    make_frame("B,11,1600,1,-125,32767,1000,-125", text, sizeof(text));
    result = feed(&parser, text, &frame);
    assert(result == CAMERA_PARSE_FRAME);
    assert(frame.seq == 11U);
    assert(frame.pos_mm == -125);
    assert(frame.vel_mm_s == 32767);
    assert(frame.target_mm == -125);

    puts("camera protocol tests: OK");
    return 0;
}
